version: '3.8'

volumes:
  data_volume:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: koloyojik/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: koloyojik/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend
