version: '3.8'

volumes:
  data_value:
  static_value:
  media_value:
  redoc:

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: koloyojik/foodgram_backend:latest
    restart: always
    volumes:
      - redoc:/app/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: koloyojik/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
